spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onboarding_dev
    username: onboard
    password: change_me
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Use this profile when running with docker-compose postgres


